[patch]
id = "script-extender"
name = "Lane's KotOR Script Extender"
version = "1.0.1"
author = "Lane"
description = "Adds additional NWScript commands."

requires = []

conflicts = []

[patch.supported_versions]
kotor1_gog_103 = "9C10E0450A6EECA417E036E3CDE7474FED1F0A92AAB018446D156944DEA91435"
kotor1_cdcrack_103 = "761F9466F456A83909036BAEBB5C43167D722387BE66E54617BA20A8C49E9886"