[patch]
id = "repeating-blaster-fix-mh"
name = "Repeating Blaster Fix (main-hand)"
version = "0.2.0"
author = "Lane"
description = "Gives an additional Main-Hand attack to the repeating blasters."

requires = []
conflicts = []

[patch.supported_versions]
kotor1_gog_103 = "9C10E0450A6EECA417E036E3CDE7474FED1F0A92AAB018446D156944DEA91435"
kotor1_steam_103 = "34E6D971C034222A417995D8E1E8FDD9F8781795C9C289BD86C499A439F34C88"
