[[hooks]]
address = 0x00543848
type = "simple"
original_bytes = [0xc7, 0x05, 0x34, 0x28, 0x83, 0x00, 0x01, 0x00, 0x00, 0x00]
replacement_bytes = [0xc7, 0x05, 0x34, 0x28, 0x83, 0x00, 0x00, 0x00, 0x00, 0x00]

[[hooks]]
address = 0x00543846
type = "simple"
original_bytes = [0x6a, 0x01]
replacement_bytes = [0x6a, 0x00]
