[[hooks]]
address = 0x004d2b16
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x75, 0x05 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06,
					0x74, 0x07, # Jump to end
					0xb8, 0x21, 0x2b, 0x4d, 0x00, # MOV EAX, 0x004d2b21
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"
exclude_from_restore = []

[[hooks]]
address = 0x004d5043
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x75, 0x07 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06,
					0x74, 0x07, # Jump to end
					0xb8, 0x50, 0x50, 0x4d, 0x00, # MOV EAX, 0x004d5050
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"
exclude_from_restore = []

[[hooks]]
address = 0x004e568d
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x75, 0x63 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06,
					0x74, 0x07, # Jump to end
					0xb8, 0xf6, 0x56, 0x4e, 0x00, # MOV EAX, 0x004E56F6
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"
exclude_from_restore = []

[[hooks]]
address = 0x004e582c
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x75, 0x5d ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x74, 0x07, # Jump to end
					0xb8, 0x8f, 0x5e, 0x4e, 0x00, # MOV EAX, 0x004e588f
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"
exclude_from_restore = []

[[hooks]]
address = 0x004e5a79
original_bytes = [ 0x8a, 0x40, 0x08, 0x3c, 0x03, 0x75, 0x63 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x74, 0x07, # Jump to end
					0xb8, 0xe3, 0x5a, 0x4e, 0x00, # MOV EAX, 0x004e5ae3
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x004e5bcf
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x75, 0x5d ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x74, 0x07, # Jump to end
					0xb8, 0x32, 0x5c, 0x4e, 0x00, # MOV EAX, 0x004e5c32
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x004e5df0
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x8b, 0x5c, 0x24, 0x34, 0x8b, 0x6c, 0x24, 0x2c, 0x75, 0x59 ]
replacement_bytes = [
					0x8b, 0x5c, 0x24, 0x34,
					0x8b, 0x6c, 0x24, 0x2c,
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x74, 0x07, # Jump to end
					0xb8, 0x57, 0x5e, 0x4e, 0x00, # MOV EAX, 0x004e5e57
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x004e6037
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x8b, 0x5c, 0x24, 0x3c, 0x8b, 0x6c, 0x24, 0x34, 0x75, 0x59 ]
replacement_bytes = [
					0x8b, 0x5c, 0x24, 0x3c,
					0x8b, 0x6c, 0x24, 0x34,
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x74, 0x07, # Jump to end
					0xb8, 0x9e, 0x60, 0x4e, 0x00, # MOV EAX, 0x004e609e
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x004e623b
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x8b, 0x5c, 0x24, 0x3c, 0x8b, 0x6c, 0x24, 0x34, 0x75, 0x59 ]
replacement_bytes = [
					0x8b, 0x5c, 0x24, 0x3c,
					0x8b, 0x6c, 0x24, 0x34,
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x74, 0x07, # Jump to end
					0xb8, 0xa2, 0x62, 0x4e, 0x00, # MOV EAX, 0x004e62a2
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x004e70fd
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x8b, 0x5c, 0x24, 0x38, 0x8b, 0x6c, 0x24, 0x30, 0x75, 0x59 ]
replacement_bytes = [
					0x8b, 0x5c, 0x24, 0x38,
					0x8b, 0x6c, 0x24, 0x30,
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x74, 0x07, # Jump to end
					0xb8, 0x64, 0x71, 0x4e, 0x00, # MOV EAX, 0x004e7164
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x00500fd9
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x75, 0x10 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x74, 0x07, # Jump to end
					0xb8, 0xef, 0x0f, 0x50, 0x00, # MOV EAX, 0x00500fef
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x005a5175
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x74, 0x12 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x06, # Jump to MOV
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x75, 0x07, # Jump to end
					0xb8, 0x8d, 0x51, 0x5a, 0x00, # MOV EAX, 0x005a518d
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x005a52ea
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x74, 0x12 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x06, # Jump to MOV
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x75, 0x07, # Jump to end
					0xb8, 0x02, 0x53, 0x5a, 0x00, # MOV EAX, 0x005a5302
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x005a7912
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x75, 0x05 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x74, 0x07, # Jump to end
					0xb8, 0x1d, 0x79, 0x5a, 0x00, # MOV EAX, 0x005a791d
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x005a7a58
original_bytes = [ 0x38, 0x58, 0x08, 0x74, 0x3f ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x06, # Jump to MOV
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x75, 0x07, # Jump to end
					0xb8, 0x9c, 0x7a, 0x5a, 0x00, # MOV EAX, 0x005a7a9c
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x005a7af0
original_bytes = [ 0x38, 0x58, 0x08, 0x74, 0x24 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x06, # Jump to MOV
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x75, 0x07, # Jump to end
					0xb8, 0x19, 0x7b, 0x5a, 0x00, # MOV EAX, 0x005a7b19
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x005a7c39
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x75, 0x05 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x74, 0x07, # Jump to end
					0xb8, 0x44, 0x7c, 0x5a, 0x00, # MOV EAX, 0x005a7c44
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x005a806a
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x74, 0x02 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x06, # Jump to MOV
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x75, 0x07, # Jump to end
					0xb8, 0x72, 0x80, 0x5a, 0x00, # MOV EAX, 0x005a8072
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x005a80de
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x75, 0x10 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x74, 0x07, # Jump to end
					0xb8, 0xf4, 0x80, 0x5a, 0x00, # MOV EAX, 0x005a80f4
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x005ae301
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x74, 0x11 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x06, # Jump to MOV
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x75, 0x07, # Jump to end
					0xb8, 0x18, 0xe3, 0x5a, 0x00, # MOV EAX, 0x005ae318
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x005ae586
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x74, 0x18 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x06, # Jump to MOV
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x75, 0x07, # Jump to end
					0xb8, 0xa4, 0xe5, 0x5a, 0x00, # MOV EAX, 0x005ae5a4
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x006b9aaa
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x75, 0x08 ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x74, 0x07, # Jump to end
					0xb8, 0xb8, 0x9a, 0x6b, 0x00, # MOV EAX, 0x006b9ab8
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"

[[hooks]]
address = 0x006b9c13
original_bytes = [ 0x80, 0x78, 0x08, 0x03, 0x75, 0x1f ]
replacement_bytes = [
					0x80, 0x78, 0x08, 0x03, # Compare to 3
					0x74, 0x0d, # Jump to end
					0x80, 0x78, 0x08, 0x06, # Compare to 6
					0x74, 0x07, # Jump to end
					0xb8, 0x38, 0x9c, 0x6b, 0x00, # MOV EAX, 0x006b9c38
					0xff, 0xe0 # Jump to EAX
					]
type = "replace"