# LightManager::maxLights
[[hooks]]
address = 0x00a0fb64
type = "simple"
original_bytes = [0x03, 0x00, 0x00, 0x00]
replacement_bytes = [0x07, 0x00, 0x00, 0x00]

# LightManager::PrioritizeIllumination
[[hooks]]
address = 0x009006dc
type = "simple"
original_bytes = [0x83, 0x7d, 0xf0, 0x03]
replacement_bytes = [0x83, 0x7d, 0xf0, 0x07]

# Scene::DoGobBuckets
[[hooks]]
address = 0x0085a492
type = "simple"
original_bytes = [0x6a, 0x03]
replacement_bytes = [0x6a, 0x07]

[[hooks]]
address = 0x0085a4af
type = "simple"
original_bytes = [0x6a, 0x03]
replacement_bytes = [0x6a, 0x07]

[[hooks]]
address = 0x0085a50b
type = "simple"
original_bytes = [0x6a, 0x03]
replacement_bytes = [0x6a, 0x07]

# Scene::DoBlurBuckets
[[hooks]]
address = 0x0085ab0f
type = "simple"
original_bytes = [0x6a, 0x03]
replacement_bytes = [0x6a, 0x07]

# Scene::DoLightSaberBucket
[[hooks]]
address = 0x00859ad7
type = "simple"
original_bytes = [0x6a, 0x03]
replacement_bytes = [0x6a, 0x07]

[[hooks]]
address = 0x00859af4
type = "simple"
original_bytes = [0x6a, 0x03]
replacement_bytes = [0x6a, 0x07]

# LightManager::EnableHighestPriorityLightsFade
[[hooks]]
address = 0x0090105e
type = "simple"
original_bytes = [0x83, 0x7d, 0xec, 0x03]
replacement_bytes = [0x83, 0x7d, 0xec, 0x07]

# LightManager::EnableHighestPriorityLights
[[hooks]]
address = 0x009009ac
type = "simple"
original_bytes = [0x83, 0x7d, 0xf8, 0x03]
replacement_bytes = [0x83, 0x7d, 0xf8, 0x07]

# LightManager::GetNearestLights
[[hooks]]
address = 0x00903b71
type = "simple"
original_bytes = [0x83, 0x7d, 0xf8, 0x03]
replacement_bytes = [0x83, 0x7d, 0xf8, 0x07]

[[hooks]]
address = 0x00903c73
type = "simple"
original_bytes = [0x83, 0x7d, 0xfc, 0x03]
replacement_bytes = [0x83, 0x7d, 0xfc, 0x07]

# LightManager::ControlLightsFade
[[hooks]]
address = 0x00901f21
type = "simple"
original_bytes = [0x83, 0x7d, 0xf0, 0x03]
replacement_bytes = [0x83, 0x7d, 0xf0, 0x07]
