[metadata]
target_versions = [
	"9C10E0450A6EECA417E036E3CDE7474FED1F0A92AAB018446D156944DEA91435",
	"761F9466F456A83909036BAEBB5C43167D722387BE66E54617BA20A8C49E9886"
]

[[hooks]]
address = 0x006fb4ce
function = "InitializeAdditionalCommands"
original_bytes = [0x89, 0x45, 0xe0, 0x3b, 0xc6]
type = "detour"
exclude_from_restore = []

