[patch]
id = "additional-console-commands"
name = "Additional Console Commands"
version = "1.3.0"
author = "Lane"
description = "Adds additional commands to the in-game cheat console"

requires = []

conflicts = []

[patch.supported_versions]
kotor1_gog_103 = "9C10E0450A6EECA417E036E3CDE7474FED1F0A92AAB018446D156944DEA91435"
kotor2_gog_aspyr = "777BEE235A9E8BDD9863F6741BC3AC54BB6A113B62B1D2E4D12BBE6DB963A914"