[patch]
id = "additional-console-commands"
name = "Additional Console Commands"
version = "1.0.0"
author = "Lane"
description = "Adds additional commands to the in-game cheat console"

requires = []

conflicts = []

[patch.supported_versions]
kotor1_gog_103 = "9C10E0450A6EECA417E036E3CDE7474FED1F0A92AAB018446D156944DEA91435"