[patch]
id = "replies-past-9"
name = "Numbered Dialogue Replies Past 9"
version = "1.0.0"
author = "Lane"
description = "Replaces the '-' prefix for replies with index greater than 9, with an actual number"

requires = []

conflicts = []

[patch.supported_versions]
kotor1_gog_103 = "9C10E0450A6EECA417E036E3CDE7474FED1F0A92AAB018446D156944DEA91435"
kotor1_steam_103 = "34E6D971C034222A417995D8E1E8FDD9F8781795C9C289BD86C499A439F34C88"
kotor1_cdcrack_103 = "761F9466F456A83909036BAEBB5C43167D722387BE66E54617BA20A8C49E9886"